# Generated by Django 4.2.15 on 2024-08-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='escolaridade',
            field=models.CharField(max_length=100),
        ),
    ]
