# Generated by Django 4.2.15 on 2024-08-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_inscricao_escolaridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=11)),
                ('CEP', models.IntegerField()),
                ('telefone', models.IntegerField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(max_length=100)),
                ('nomeFantasia', models.CharField(max_length=100)),
                ('CNPJ', models.IntegerField()),
                ('CEP', models.IntegerField()),
                ('telefone', models.IntegerField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.FileField(upload_to='')),
                ('quantidade', models.IntegerField()),
                ('precoCompra', models.IntegerField()),
                ('precoVenda', models.IntegerField()),
                ('forcenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.fornecedor')),
            ],
        ),
    ]
