# Generated by Django 5.1.1 on 2024-09-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_estoquemovimentacao_itemvenda_lote_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
