# Generated by Django 4.2.16 on 2024-09-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_cliente_cpf_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='preco_unitario',
        ),
    ]
