# Generated by Django 4.2.16 on 2024-09-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_itemvenda_preco_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='CNPJ',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartão de crédito', 'Cartão de Crédito'), ('cartão de débito', 'Cartão de Débito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
